import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Phone,MapPin,Clock,ArrowUpRight,Search,ChevronDown,Utensils,CalendarDays,Hotel,Menu as MenuIcon,X,MessageCircle} from 'lucide-react';
import './styles.css';

const phone='0333-2566671';
const wa='923332566671';
const categories=[
['all','All Menu'],['limca','Limca Soda'],['juice','Fresh Juice'],['shake','Fresh Milk Shake'],['margarita','Margarita'],['ice-shake','Ice Cream Shake'],['ice-cream','Ice Cream'],['pizza','Pizza'],['karahi','Chicken Karahi & Handi'],['mutton','Mutton Karahi'],['bbq','BBQ & Tikka'],['chinese','Chinese & Rice'],['veg','Vegetable & Dall'],['paneer','Paneer'],['roll','Roll'],['roti','Roti / Paratha'],['fast','Fast Food & More']
];
const menu=[
{c:'limca',n:'Strawberry',p:'160'},{c:'limca',n:'Mint',p:'160'},{c:'limca',n:'Peach',p:'160'},{c:'limca',n:'Leman',p:'160'},{c:'limca',n:'Blue Berry',p:'160'},{c:'limca',n:'Pakola',p:'160'},{c:'limca',n:'Cocktal Soda',p:'160'},
{c:'juice',n:'Orange Juice',p:'150'},{c:'juice',n:'Apple Juice',p:'250'},
{c:'shake',n:'Diamond SP Power Shake',p:'400',featured:1},{c:'shake',n:'Khajoor',p:'250'},{c:'shake',n:'Banana',p:'180'},{c:'shake',n:'Apple',p:'250'},{c:'shake',n:'Mango',p:'180'},{c:'shake',n:'Papeta',p:'180'},{c:'shake',n:'Pine Apple',p:'200'},{c:'shake',n:'Mix Fruit',p:'200'},
{c:'margarita',n:'Blue Berry',p:'200'},{c:'margarita',n:'Mint',p:'200'},{c:'margarita',n:'Lemonaid',p:'180'},{c:'margarita',n:'Peach',p:'180'},
...['Strawberry','Pista','Mango','Karanch','Chocolate','Vanilla','Oreo','Kulfa','Cold Coffee'].map(n=>({c:'ice-shake',n,p:'350'})),
{c:'ice-cream',n:'Diamond Special Falooda',p:'350',featured:1},{c:'ice-cream',n:'Diamond Special Ice Cream',p:'350',featured:1},
...['Pista','Mango','Vanilla','Chocolate','Karanch','Kulfa','Caramel Cookies'].map(n=>({c:'ice-cream',n,p:'220'})),{c:'ice-cream',n:'Half Liter',p:'600'},{c:'ice-cream',n:'Full Liter',p:'1200'},
{c:'pizza',n:'Chicken Stuff Crust',p:'1000 / 1400',size:'M / L'},{c:'pizza',n:'Crown Crust',p:'1000 / 1400',size:'M / L'},{c:'pizza',n:'Extreme',p:'1200 / 1600',size:'M / L'},{c:'pizza',n:'Paneer Crust',p:'1000 / 1400',size:'M / L'},{c:'pizza',n:'Creamy Stuff',p:'1000 / 1400',size:'M / L'},{c:'pizza',n:'Kabab Crust',p:'1000 / 1400',size:'M / L'},{c:'pizza',n:'Chicken Stick',p:'900'},{c:'pizza',n:'Chicken Kabab Stick',p:'950'},{c:'pizza',n:'Special Pizza Roll',p:'550'},
{c:'karahi',n:'Chicken Karahi / Brown',p:'900 / 1800'},{c:'karahi',n:'Green / White / Shanwari / Pishawari / Achari',p:'1000 / 2000'},{c:'karahi',n:'Boneless Handi — White Makhni / Achar / Reshmi',p:'1050 / 2100'},
{c:'mutton',n:'Mutton Karahi / Brown / Achari',p:'1700 / 3400',size:'H / F'},{c:'mutton',n:'Green / Shinwari / Peshawari',p:'1800 / 3600',size:'H / F'},{c:'mutton',n:'Boneless Handi',p:'1800 / 3600',size:'H / F'},
{c:'bbq',n:'Chicken Tikka — Leg',p:'460'},{c:'bbq',n:'Chicken Tikka — Chest',p:'500'},{c:'bbq',n:'Malai',p:'600'},{c:'bbq',n:'Qalmi',p:'400'},{c:'bbq',n:'Boti',p:'400'},{c:'bbq',n:'Behari / Afghani / Malai / Green Boti',p:'430 – 480'},{c:'bbq',n:'Reshmi / Gola Kabab',p:'750'},{c:'bbq',n:'Fish Grilled',p:'1800',size:'Kg'},{c:'bbq',n:'BBQ Family Platter',p:'1800 / 3600'},{c:'bbq',n:'Chicken Grilled Charga',p:'2000',size:'Kg'},
{c:'chinese',n:'Chicken Chilli / Manchurian / Shashlic / Jalfrezi with Rice',p:'900'},{c:'chinese',n:'Chicken Chowmein',p:'550'},{c:'chinese',n:'Veg Noodles',p:'500'},{c:'chinese',n:'Chicken Noodles',p:'600'},{c:'chinese',n:'Fried Rice — Veg / Egg / Chicken',p:'350 / 400 / 450'},{c:'chinese',n:'Biryani — Chicken / Mutton / Aallo',p:'450 / 850 / 350'},{c:'chinese',n:'Pulao — Chicken / Mutton',p:'600 / 1100'},
{c:'veg',n:'Mix Veg Plate',p:'200'},{c:'veg',n:'Veg Handi / Karahi',p:'800 / 1600'},{c:'veg',n:'Veg Kofta Handi',p:'850 / 1700'},{c:'veg',n:'Dall Fry',p:'200'},{c:'veg',n:'Dall Makhni / Achari Handi',p:'400 / 800 / 1600'},{c:'veg',n:'Chicken Shahi Dall',p:'800 / 1600'},
{c:'paneer',n:'Paneer Handi — Makhni / Reshmi / Shahi / Palak / White / Lemon',p:'1000 / 2000'},{c:'paneer',n:'Cheese Kofta',p:'1050 / 2100'},
{c:'roll',n:'Chatni',p:'220'},{c:'roll',n:'Mayo Garlic',p:'220'},{c:'roll',n:'Malai Boti',p:'260'},{c:'roll',n:'Reshmi',p:'280'},{c:'roll',n:'Zinger',p:'260'},{c:'roll',n:'Shahi Paneer',p:'260'},{c:'roll',n:'Veg',p:'200'},
{c:'roti',n:'Chapati',p:'25'},{c:'roti',n:'Tandoori Roti',p:'50'},{c:'roti',n:'Naan',p:'50'},{c:'roti',n:'Rogni / Garlic / Zeera Naan',p:'60'},{c:'roti',n:'Plain Paratha',p:'70'},{c:'roti',n:'Aallo',p:'300'},{c:'roti',n:'Chicken',p:'400'},{c:'roti',n:'Pizza Paratha',p:'550'},{c:'roti',n:'Pori',p:'120'},
{c:'fast',n:'Burger / Sandwich / Broast',p:'430 – 760'},{c:'fast',n:'Fries',p:'200 – 600'},{c:'fast',n:'Fish Karahi',p:'950 / 1900'},{c:'fast',n:'Fish Finger',p:'1000'},{c:'fast',n:'Soup',p:'350 – 400'},{c:'fast',n:'Green Salad',p:'100'},{c:'fast',n:'Russian Salad',p:'600'},{c:'fast',n:'Raita',p:'80'}
];
const catName=Object.fromEntries(categories.map(x=>[x[0],x[1]]));
const imageMap={pizza:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1400&q=85',restaurant:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1800&q=85',bbq:'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=85',dessert:'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=1200&q=85'};

function App(){
 const [active,setActive]=useState('all'); const [q,setQ]=useState(''); const [open,setOpen]=useState(false);
 const filtered=useMemo(()=>menu.filter(i=>(active==='all'||i.c===active)&&i.n.toLowerCase().includes(q.toLowerCase())),[active,q]);
 return <div className="site">
  <div className="announcement"><span>DIAMOND HOTEL • RESTAURANT • EVENT MANAGEMENT</span><a href={`tel:${phone}`}>Call {phone}</a></div>
  <header className="nav"><a className="brand" href="#top"><span className="brand-mark">D</span><span><b>DIAMOND</b><small>HOTEL · RESTAURANT · EVENTS</small></span></a><button className="mobile-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</button><nav className={open?'open':''}>{[['Menu','#menu'],['About','#about'],['Events','#events'],['Contact','#contact']].map(([t,h])=><a key={t} href={h} onClick={()=>setOpen(false)}>{t}</a>)}<a className="nav-cta" href={`https://wa.me/${wa}?text=Hello%20Diamond%20Hotel%2C%20I%20would%20like%20to%20ask%20about%20your%20menu.`}>WhatsApp <ArrowUpRight size={16}/></a></nav></header>
  <main id="top">
   <section className="hero"><div className="hero-bg"></div><div className="hero-overlay"></div><div className="hero-content reveal"><div className="eyebrow"><span></span> MATLI · 2JVM+QQH</div><h1>Good food.<br/><em>Good moments.</em></h1><p>TASTY & DELICIOUS FOOD</p><div className="hero-actions"><a href="#menu" className="primary">Explore Menu <ArrowUpRight size={18}/></a><a href={`tel:${phone}`} className="ghost"><Phone size={17}/> Call us</a></div></div><div className="hero-stamp">DIAMOND<br/><small>EST. MATLI</small></div></section>
   <div className="marquee" data-anim-marquee data-anim-marquee-pause><div><span>FRESH FLAVOURS</span><i>✦</i><span>FAMILY DINING</span><i>✦</i><span>EVENT MANAGEMENT</span><i>✦</i><span>DIAMOND SPECIALS</span><i>✦</i><span>FRESH FLAVOURS</span><i>✦</i></div></div>
   <section className="intro section" id="about"><div className="intro-copy reveal"><div className="section-kicker">THE DIAMOND EXPERIENCE</div><h2>From a quick bite<br/>to a <em>full table.</em></h2><p>Diamond brings together a broad menu of drinks, pizzas, karahi, BBQ, Chinese, rice, desserts and fast food — all in one place in Matli.</p><div className="info-row"><div><Hotel size={20}/><span>Hotel</span></div><div><Utensils size={20}/><span>Restaurant</span></div><div><CalendarDays size={20}/><span>Events</span></div></div></div><div className="intro-card reveal"><img src={imageMap.restaurant} alt="Restaurant dining"/><div><b>Made for moments.</b><span>Dining · Gatherings · Events</span></div></div></section>
   <section className="menu-section section" id="menu"><div className="section-head reveal"><div><div className="section-kicker">THE MENU</div><h2>Choose your <em>favourite.</em></h2></div><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search menu…"/></div></div><div className="cat-wrap"><div className="cats">{categories.map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}>{label}</button>)}</div></div><div className="menu-meta"><span>{filtered.length} items</span><span>Prices as provided by Diamond</span></div><div className="menu-grid">{filtered.map((item,i)=><article className={`dish ${item.featured?'featured':''}`} key={i}><div className="dish-top"><span className="dish-cat">{catName[item.c]}</span>{item.featured&&<span className="special">DIAMOND SPECIAL</span>}</div><h3>{item.n}</h3><div className="dish-bottom"><span className="price">Rs {item.p}</span>{item.size&&<small>{item.size}</small>}</div></article>)}</div></section>
   <section className="feature-band"><div className="feature-image" style={{backgroundImage:`url(${imageMap.pizza})`}}></div><div className="feature-copy"><div className="section-kicker">DIAMOND SPECIAL</div><h2>Bring everyone<br/><em>to the table.</em></h2><p>Planning a family gathering, dinner or event? Diamond Hotel, Restaurant & Event Management is ready to help.</p><a href={`https://wa.me/${wa}?text=Hello%20Diamond%20Hotel%2C%20I%20want%20to%20ask%20about%20an%20event.`} className="primary">Plan an Event <ArrowUpRight size={18}/></a></div></section>
   <section className="contact section" id="events"><div className="contact-head"><div className="section-kicker">HOTEL · EVENTS · DINING</div><h2>Let's make it<br/><em>Diamond.</em></h2></div><div className="contact-grid"><a href={`tel:${phone}`}><span className="icon"><Phone/></span><small>CALL</small><b>0333-2566671</b></a><a href="tel:0232261215"><span className="icon"><Phone/></span><small>ALTERNATE</small><b>0232-261215</b></a><a href="https://maps.google.com/?q=2JVM%2BQQH%20Matli" target="_blank" rel="noreferrer"><span className="icon"><MapPin/></span><small>LOCATION</small><b>Matli · 2JVM+QQH</b></a><a href={`https://wa.me/${wa}`}><span className="icon"><MessageCircle/></span><small>WHATSAPP</small><b>Message Diamond</b></a></div></section>
  </main>
  <footer id="contact"><div className="footer-brand"><span className="brand-mark">D</span><div><b>DIAMOND</b><small>HOTEL · RESTAURANT · EVENT MANAGEMENT</small></div></div><p>TASTY & DELICIOUS FOOD</p><div>© {new Date().getFullYear()} Diamond Hotel, Restaurant & Event Management</div></footer>
  <a className="float-wa" href={`https://wa.me/${wa}`} aria-label="WhatsApp"><MessageCircle/></a>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
